import { Cabane } from '../types/cabane';

export const MOCK_CABANES: Cabane[] = [
  {
    id: '1',
    nom: 'La Petite Bibliothèque du Marais',
    type: 'livres',
    description: 'Une jolie cabane en bois peinte en bleu, nichée dans une ruelle pavée. Romans, BD, policiers — plus de 150 titres en permanence. Entretenue avec amour par les habitants du quartier.',
    latitude: 48.856, longitude: 2.354,
    ville: 'Paris', region: 'Île-de-France',
    contributeur: 'Marie', signalements: 0, featured: true,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: '2',
    nom: 'Cabane Solidaire Place Bellecour',
    type: 'dons',
    description: 'Vêtements, jouets et conserves toujours bienvenus. Prenez ce dont vous avez besoin, donnez ce que vous pouvez. Ouverte 24h/24, gérée par l\'association "Lyon Partage".',
    latitude: 45.757, longitude: 4.832,
    ville: 'Lyon', region: 'Auvergne-Rhône-Alpes',
    contributeur: 'Julien', signalements: 0, featured: true,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: '3',
    nom: 'Le Coffre aux Trésors',
    type: 'mixte',
    description: 'Livres, vêtements et objets divers. Une cabane magique entretenue par les voisins du quartier ! On y trouve souvent de belles surprises — vinyles, cartes postales, livres de cuisine du monde.',
    latitude: 43.296, longitude: 5.381,
    ville: 'Marseille', region: 'Provence-Alpes-Côte d\'Azur',
    contributeur: 'Sophie', signalements: 0, featured: true,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: '4',
    nom: 'Boîte à Livres du Capitole',
    type: 'livres',
    description: 'Nichée dans une vieille cabine téléphonique rénovée aux couleurs de Toulouse, cette boîte à livres propose romans, guides de voyage et ouvrages en occitan.',
    latitude: 43.605, longitude: 1.444,
    ville: 'Toulouse', region: 'Occitanie',
    contributeur: 'Pierre', signalements: 0, featured: false,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: '5',
    nom: 'La Ruche Généreuse',
    type: 'dons',
    description: 'Alimentée par le quartier Saint-Michel, toujours bien fournie en conserves, produits ménagers et vêtements de saison. Une ruche de générosité au cœur de Bordeaux.',
    latitude: 44.838, longitude: -0.579,
    ville: 'Bordeaux', region: 'Nouvelle-Aquitaine',
    contributeur: 'Amandine', signalements: 0, featured: false,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: '6',
    nom: 'Ar Skeudenn — La Bibliothèque Bretonne',
    type: 'mixte',
    description: 'Livres en français et en breton, romans régionaux, polars et BD. Quelques vêtements et jouets pour enfants en prime. Un espace de partage ancré dans la culture bretonne.',
    latitude: 48.117, longitude: -1.677,
    ville: 'Rennes', region: 'Bretagne',
    contributeur: 'Erwan', signalements: 0, featured: true,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: '7',
    nom: 'Le Nichoir à Romans',
    type: 'livres',
    description: 'Plus de 200 livres en permanence. Romans contemporains, essais, jeunesse et classiques. Venez piocher et déposer ! Réapprovisionnée toutes les semaines par une vingtaine de bénévoles.',
    latitude: 47.218, longitude: -1.554,
    ville: 'Nantes', region: 'Pays de la Loire',
    contributeur: 'Lucie', signalements: 0, featured: false,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: '8',
    nom: 'Don et Partage Vieux-Lille',
    type: 'dons',
    description: 'Cabane solidaire dans le quartier historique. Dons alimentaires, vestimentaires et scolaires acceptés. Gérée par un collectif de riverains depuis 2021.',
    latitude: 50.637, longitude: 3.063,
    ville: 'Lille', region: 'Hauts-de-France',
    contributeur: 'Mathieu', signalements: 0, featured: false,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: '9',
    nom: 'La Malle aux Mots',
    type: 'livres',
    description: 'Une ancienne malle de voyage reconvertie en bibliothèque de rue. Thrillers, romances, développement personnel… Installée à deux pas du marché couvert.',
    latitude: 43.124, longitude: 5.928,
    ville: 'Toulon', region: 'Provence-Alpes-Côte d\'Azur',
    contributeur: 'Céline', signalements: 0, featured: false,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: '10',
    nom: 'Partage & Lumière',
    type: 'mixte',
    description: 'Livres scientifiques, romans et objets du quotidien. Cette cabane est spécialement enrichie après chaque vide-grenier du quartier. Un must du partage strasbourgeois.',
    latitude: 48.573, longitude: 7.752,
    ville: 'Strasbourg', region: 'Grand Est',
    contributeur: 'Klaus', signalements: 0, featured: false,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: '11',
    nom: 'Le Grenier Solidaire',
    type: 'dons',
    description: 'Textiles, vaisselle, jouets et petite électroménager fonctionnel. Tout objet propre et en état est accepté. Bénévoles présents le samedi matin pour accueillir les dons.',
    latitude: 45.188, longitude: 5.724,
    ville: 'Grenoble', region: 'Auvergne-Rhône-Alpes',
    contributeur: 'Fabienne', signalements: 0, featured: false,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: '12',
    nom: 'La Cabane Normande',
    type: 'livres',
    description: 'Construite en chêne local par un menuisier bénévole, cette bibliothèque de rue trône depuis 3 ans sur la place du village. Elle accueille romans, livres de recettes normandes et ouvrages agricoles.',
    latitude: 49.443, longitude: 1.099,
    ville: 'Rouen', region: 'Normandie',
    contributeur: 'Bernard', signalements: 0, featured: false,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];
